name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: navigate to project
      run: cd ./2_C#/gui
    - name: debug
      run: dir/w
    - name: Restore dependencies
      run: dotnet restore ./2_C#/gui
    - name: Build
      run: dotnet build --no-restore ./2_C#/gui
    - name: Test
      run: dotnet test --no-build --verbosity normal ./2_C#/gui
    - name: upload project artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads
