name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: restore project
      run: dotnet restore ./2_C#/gui
    - name: build project
      run: dotnet build --no-restore ./2_C#/gui
    - name: upload project artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: gui
        path: ./2_C#/gui/bin/Debug/net6.0-windows
